-- =============================================================================
-- Restaurant QR Ordering & Management System - full schema
-- Matches the JPA entities in com.restro.entity exactly, table for table,
-- column for column. Generated by hand from the entity source (not by
-- Hibernate's ddl-auto), for deployments that want an explicit, reviewable
-- migration instead of relying on ddl-auto=update.
--
-- Usage:
--   1. CREATE DATABASE rest_db; (or your own name)
--   2. mysql -u root -p rest_db < schema.sql
--   3. In application.properties, set spring.jpa.hibernate.ddl-auto=validate
--      (NOT update/create) so Hibernate checks against this schema instead
--      of trying to auto-migrate it.
--   4. Optionally load sql/seed-demo-menu.sql afterwards for demo data.
-- =============================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------------------------------
-- restaurant (1 row per deployment)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS restaurant (
    restaurant_id           INT AUTO_INCREMENT PRIMARY KEY,
    name                     VARCHAR(150)   NOT NULL,
    logo_path                VARCHAR(255),
    banner_path               VARCHAR(255),
    address                  VARCHAR(500),
    phone                    VARCHAR(20),
    email                    VARCHAR(150),
    gstin                    VARCHAR(20),
    upi_id                   VARCHAR(100),
    currency_code            VARCHAR(10)    NOT NULL DEFAULT 'INR',
    currency_symbol          VARCHAR(5)     NOT NULL DEFAULT '₹',
    service_charge_percent   DECIMAL(5,2)   NOT NULL DEFAULT 0.00,
    theme_color              VARCHAR(20)    NOT NULL DEFAULT '#c0392b',
    dark_mode_default        TINYINT(1)     NOT NULL DEFAULT 0,
    opening_time             TIME,
    closing_time             TIME,
    is_open                  TINYINT(1)     NOT NULL DEFAULT 1,
    created_at               DATETIME       NOT NULL,
    updated_at               DATETIME       NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- owner (single-login owner account)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS owner (
    owner_id        INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT           NOT NULL,
    email            VARCHAR(150)  NOT NULL UNIQUE,
    password_hash    VARCHAR(255)  NOT NULL,
    full_name        VARCHAR(150),
    is_active        TINYINT(1)    NOT NULL DEFAULT 1,
    last_login_at    DATETIME,
    created_at       DATETIME      NOT NULL,
    CONSTRAINT fk_owner_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- settings (misc key/value toggles)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
    setting_id      INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT           NOT NULL,
    setting_key     VARCHAR(100)  NOT NULL,
    setting_value   VARCHAR(1000),
    CONSTRAINT fk_settings_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id),
    CONSTRAINT uq_settings_restaurant_key UNIQUE (restaurant_id, setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- category
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS category (
    category_id     INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT           NOT NULL,
    name            VARCHAR(100)  NOT NULL,
    display_order   INT           NOT NULL DEFAULT 0,
    image_path      VARCHAR(255),
    is_active       TINYINT(1)    NOT NULL DEFAULT 1,
    created_at      DATETIME      NOT NULL,
    updated_at      DATETIME      NOT NULL,
    CONSTRAINT fk_category_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id),
    CONSTRAINT uq_category_restaurant_name UNIQUE (restaurant_id, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- food_item
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food_item (
    food_item_id        INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id       INT            NOT NULL,
    category_id         INT            NOT NULL,
    name                VARCHAR(150)   NOT NULL,
    description         VARCHAR(1000),
    ingredients         VARCHAR(1000),
    price               DECIMAL(10,2)  NOT NULL,
    offer_price         DECIMAL(10,2),
    prep_time_minutes   INT            NOT NULL DEFAULT 15,
    food_type           VARCHAR(20)    NOT NULL DEFAULT 'VEG',       -- enum: VEG, NON_VEG, EGG
    spice_level         VARCHAR(20)    NOT NULL DEFAULT 'MEDIUM',    -- enum: MILD, MEDIUM, HOT, EXTRA_HOT
    is_available        TINYINT(1)     NOT NULL DEFAULT 1,
    is_recommended       TINYINT(1)     NOT NULL DEFAULT 0,
    is_bestseller        TINYINT(1)     NOT NULL DEFAULT 0,
    display_order        INT            NOT NULL DEFAULT 0,
    created_at            DATETIME       NOT NULL,
    updated_at            DATETIME       NOT NULL,
    CONSTRAINT fk_food_item_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id),
    CONSTRAINT fk_food_item_category FOREIGN KEY (category_id) REFERENCES category (category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- food_image
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food_image (
    food_image_id   INT AUTO_INCREMENT PRIMARY KEY,
    food_item_id    INT           NOT NULL,
    image_path      VARCHAR(255)  NOT NULL,
    is_primary      TINYINT(1)    NOT NULL DEFAULT 0,
    display_order   INT           NOT NULL DEFAULT 0,
    created_at      DATETIME      NOT NULL,
    CONSTRAINT fk_food_image_food_item FOREIGN KEY (food_item_id) REFERENCES food_item (food_item_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- restaurant_table
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS restaurant_table (
    table_id        INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT          NOT NULL,
    table_no        VARCHAR(20)  NOT NULL,
    capacity        INT          NOT NULL DEFAULT 4,
    qr_token        VARCHAR(64)  NOT NULL,
    is_active       TINYINT(1)   NOT NULL DEFAULT 1,
    created_at      DATETIME     NOT NULL,
    CONSTRAINT fk_restaurant_table_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id),
    CONSTRAINT uq_restaurant_table_no UNIQUE (restaurant_id, table_no),
    CONSTRAINT uq_restaurant_table_qr_token UNIQUE (qr_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- qr_code (history of generated QR images per table)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS qr_code (
    qr_code_id     INT AUTO_INCREMENT PRIMARY KEY,
    table_id       INT           NOT NULL,
    image_path     VARCHAR(255)  NOT NULL,
    target_url     VARCHAR(500)  NOT NULL,
    generated_at   DATETIME      NOT NULL,
    CONSTRAINT fk_qr_code_table FOREIGN KEY (table_id) REFERENCES restaurant_table (table_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- table_session (one "visit" at a table - groups every order any phone at
-- that table placed, so billing combines them into one total instead of
-- one bill per phone. Opens with the table's first order after it was
-- last free; closes the moment its bill is settled.)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS table_session (
    table_session_id   INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id       INT           NOT NULL,
    table_id             INT           NOT NULL,
    status                VARCHAR(20)   NOT NULL DEFAULT 'OPEN',  -- enum: OPEN, CLOSED
    opened_at              DATETIME      NOT NULL,
    closed_at               DATETIME,
    CONSTRAINT fk_table_session_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id),
    CONSTRAINT fk_table_session_table FOREIGN KEY (table_id) REFERENCES restaurant_table (table_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- sequence_counter (atomic, restart-safe numbering for order/invoice numbers -
-- see SequenceService for why this replaced an in-memory counter)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sequence_counter (
    seq_key         VARCHAR(50)  PRIMARY KEY,
    current_value   BIGINT       NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- tax
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tax (
    tax_id          INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT           NOT NULL,
    name            VARCHAR(50)   NOT NULL,
    percent         DECIMAL(5,2)  NOT NULL,
    is_active       TINYINT(1)    NOT NULL DEFAULT 1,
    created_at      DATETIME      NOT NULL,
    CONSTRAINT fk_tax_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- discount
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS discount (
    discount_id     INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT            NOT NULL,
    code            VARCHAR(30)    NOT NULL,
    description     VARCHAR(255),
    discount_type   VARCHAR(20)    NOT NULL DEFAULT 'PERCENT',  -- enum: PERCENT, FLAT
    value           DECIMAL(10,2)  NOT NULL,
    is_active       TINYINT(1)     NOT NULL DEFAULT 1,
    valid_from      DATE,
    valid_to        DATE,
    created_at      DATETIME       NOT NULL,
    CONSTRAINT fk_discount_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id),
    CONSTRAINT uq_discount_restaurant_code UNIQUE (restaurant_id, code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- orders (note: plural table name - "order" is a reserved SQL keyword)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    order_id                INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id           INT            NOT NULL,
    order_no                VARCHAR(30)    NOT NULL,
    table_id                INT            NOT NULL,
    table_session_id         INT,  -- nullable only for orders placed before this feature existed
    status                  VARCHAR(20)    NOT NULL DEFAULT 'PENDING',  -- enum: PENDING, ACCEPTED, SERVED, COMPLETED, CANCELLED
    subtotal                DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
    tax_amount               DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
    service_charge_amount    DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
    discount_amount          DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
    grand_total               DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
    discount_id                INT,
    customer_note              VARCHAR(500),
    created_at                 DATETIME       NOT NULL,
    updated_at                 DATETIME       NOT NULL,
    CONSTRAINT fk_orders_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id),
    CONSTRAINT fk_orders_table FOREIGN KEY (table_id) REFERENCES restaurant_table (table_id),
    CONSTRAINT fk_orders_table_session FOREIGN KEY (table_session_id) REFERENCES table_session (table_session_id),
    CONSTRAINT fk_orders_discount FOREIGN KEY (discount_id) REFERENCES discount (discount_id),
    CONSTRAINT uq_orders_order_no UNIQUE (order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- order_item
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_item (
    order_item_id          INT AUTO_INCREMENT PRIMARY KEY,
    order_id                INT            NOT NULL,
    food_item_id             INT            NOT NULL,
    food_name_snapshot        VARCHAR(150)   NOT NULL,
    unit_price                 DECIMAL(10,2)  NOT NULL,
    quantity                   INT            NOT NULL,
    special_instructions        VARCHAR(300),
    line_total                   DECIMAL(10,2)  NOT NULL,
    created_at                    DATETIME       NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_order_item_food_item FOREIGN KEY (food_item_id) REFERENCES food_item (food_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- order_status_history (append-only lifecycle trail)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_status_history (
    history_id      INT AUTO_INCREMENT PRIMARY KEY,
    order_id        INT           NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    changed_at      DATETIME      NOT NULL,
    changed_by      VARCHAR(50),
    CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- payment (one row per settled table session - covers every order in it)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment (
    payment_id        INT AUTO_INCREMENT PRIMARY KEY,
    table_session_id   INT            NOT NULL,
    invoice_no         VARCHAR(30)    NOT NULL,
    amount             DECIMAL(10,2)  NOT NULL,
    method             VARCHAR(20)    NOT NULL DEFAULT 'CASH',  -- enum: CASH, CARD, UPI, OTHER
    payment_status     VARCHAR(20)    NOT NULL DEFAULT 'PAID',  -- enum: PAID, REFUNDED
    paid_at            DATETIME       NOT NULL,
    created_at         DATETIME       NOT NULL,
    CONSTRAINT fk_payment_table_session FOREIGN KEY (table_session_id) REFERENCES table_session (table_session_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_payment_table_session UNIQUE (table_session_id),
    CONSTRAINT uq_payment_invoice_no UNIQUE (invoice_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- uploaded_file (all images - logos, food photos, QR codes - stored as BLOBs)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS uploaded_file (
    file_id         INT AUTO_INCREMENT PRIMARY KEY,
    relative_path   VARCHAR(255)  NOT NULL,
    content_type    VARCHAR(100)  NOT NULL,
    data            LONGBLOB      NOT NULL,   -- must stay LONGBLOB, see FoodImage/UploadedFile comments
    created_at      DATETIME      NOT NULL,
    CONSTRAINT uq_uploaded_file_relative_path UNIQUE (relative_path)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- assistance_request (customer "need help" requests raised from a table)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS assistance_request (
    assistance_request_id   INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id            INT           NOT NULL,
    table_id                  INT           NOT NULL,
    request_type               VARCHAR(30)   NOT NULL,  -- enum: CALL_WAITER, CLEAN_TABLE, WATER_REFILL, REQUEST_BILL, COMPLAINT, OTHER
    message                     VARCHAR(500),
    status                       VARCHAR(20)   NOT NULL DEFAULT 'OPEN',  -- enum: OPEN, RESOLVED
    created_at                   DATETIME      NOT NULL,
    resolved_at                   DATETIME,
    CONSTRAINT fk_assistance_request_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id),
    CONSTRAINT fk_assistance_request_table FOREIGN KEY (table_id) REFERENCES restaurant_table (table_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- Indexes for the columns the live dashboard, billing, and reports filter/sort
-- on constantly. InnoDB auto-indexes plain foreign key columns, but not the
-- extra WHERE/ORDER BY columns these queries actually use, so add those
-- explicitly - without them, every dashboard poll does a full table scan of
-- `orders` once there's more than a trivial amount of history.
-- -----------------------------------------------------------------------------
CREATE INDEX idx_orders_restaurant_status ON orders (restaurant_id, status);
CREATE INDEX idx_orders_restaurant_created_at ON orders (restaurant_id, created_at);
CREATE INDEX idx_orders_table_session ON orders (table_session_id);
CREATE INDEX idx_table_session_restaurant_status ON table_session (restaurant_id, status);
CREATE INDEX idx_table_session_table_status ON table_session (table_id, status);
CREATE INDEX idx_assistance_request_restaurant_status ON assistance_request (restaurant_id, status);

SET FOREIGN_KEY_CHECKS = 1;
